[mod]
id = "eg_entity_outlines"
name = "Entity Selection Outlines"
description = "Multi-version, multi-loader mod template for Minecraft using Stonecutter."
group = "games.enchanted"
version = "1.0.0"
license = "CC BY-NC 4.0"
source_url = "https://github.com/Enchanted-Games/entity-selection-outlines"
issue_tracker = "https://github.com/Enchanted-Games/entity-selection-outlines/issues"
icon = "assets/eg_entity_outlines/icon.png"

# neoforge versions: https://projects.neoforged.net/neoforged/neoforge
# fabric versions: https://fabricmc.net/develop/

[fabric]
deps.fabric-loader = "0.19.3"
dep_str.fabric-loader = ">=0.19"


["26.1"]
deps.minecraft = "26.1.2"

[fabric."26.1"]
dep_str.minecraft = ">=26.1 <26.2"

deps.fabric-api = "0.154.2+26.1.2"
dep_str.fabric-api = ">=0.154.2+26.1.2"

deps.modmenu = "18.0.0-alpha.8"

[neoforge."26.1"]
dep_str.minecraft = "[26.1,26.2)"

deps.neoforge = "26.1.2.78"


["26.2"]
deps.minecraft = "26.2"

[fabric."26.2"]
dep_str.minecraft = ">=26.2 <26.3"

deps.fabric-api = "0.154.2+26.2"
dep_str.fabric-api = ">=0.154.2+26.2"

deps.modmenu = "20.0.0-beta.4"

[neoforge."26.2"]
dep_str.minecraft = "[26.2,26.3)"

deps.neoforge = "26.2.0.8-beta"


["26.3"]
deps.minecraft = "26.3-snapshot-3"

[fabric."26.3"]
dep_str.minecraft = ">26.2 <26.4"

# deps.fabric-api = "0.154.2+26.2"
# dep_str.fabric-api = ">=0.154.2+26.2"

# deps.modmenu = "20.0.0-beta.4"

[neoforge."26.3"]
dep_str.minecraft = "[26.2,26.3)"

deps.neoforge = "26.2.0.8-beta"

